app:
  name: abcp
  type: docker
  host: 127.0.0.1
  port: 1210
  startPort: 30000
  salt: MTQ1NzczNDIz    # 哈希加密时用到的盐，可不填

db:
  mongo:
    address: 1.12.44.120
    port: 27017
    username: "admin"
    password: "admin"
    authSource: "admin"
  redis:
    address: 1.12.44.120
    port: 6379
    password: 137248Csq!
    db: 3
  
docker:
  hub:
    host: achobeta
    username: docker
    password: docker